import {
  Activity,
  AlertTriangle,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  Bell,
  Bus,
  CarFront,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clock,
  Construction,
  Crosshair,
  Filter,
  Gauge,
  Layers,
  LayoutDashboard,
  LineChart,
  Locate,
  Map,
  MapPin,
  Radio,
  RotateCcw,
  Search,
  Settings,
  ShieldAlert,
  Signal,
  Siren,
  TrafficCone,
  TrendingUp,
  Video,
  Waves,
  Wifi,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react';

/** Named icon registry — keeps icon usage type-safe and tree-shakeable. */
export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-down-right': ArrowDownRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  bus: Bus,
  'car-front': CarFront,
  'check-circle': CheckCircle2,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  clock: Clock,
  construction: Construction,
  crosshair: Crosshair,
  filter: Filter,
  gauge: Gauge,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'line-chart': LineChart,
  locate: Locate,
  map: Map,
  'map-pin': MapPin,
  radio: Radio,
  reset: RotateCcw,
  search: Search,
  settings: Settings,
  'shield-alert': ShieldAlert,
  signal: Signal,
  siren: Siren,
  'traffic-cone': TrafficCone,
  'trending-up': TrendingUp,
  video: Video,
  waves: Waves,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? CircleDot;
}
